version: '3'
services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    ports:
      - "8080"
    command: 
      - /bin/sh
      - -c
      - |
        npm install
        npm run dev -- --host
    networks:
      - lefts

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - lefts
    ports:
      - "5000"

  reverse-proxy:
    depends_on:
      - frontend
      - backend
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./configs/reverse-dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - lefts

  mongodb:
    image: mongo:latest
    ports:
      - "27017"
    networks:
      - lefts
    volumes:
      - mongo-data:/data/db

networks:
  lefts:

volumes:
  mongo-data: