version: '3'
services:
  frontend:
    image: nginx:latest
    ports:
      - "80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ros
      - ./configs/frontend-prod.conf:/etc/nginx/nginx.conf:ro
    networks:
      - yada
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 30s

  backend:
    depends_on:
      mongodb:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - yada
    ports:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 30s

  reverse-proxy:
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./configs/reverse-prod.conf:/etc/nginx/nginx.conf:ro
    networks:
      - yada

  mongodb:
    image: mongo:latest
    ports:
      - "27017"
    networks:
      - yada
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 30s
    volumes:
      - mongo-data:/data/db

networks:
  yada:

volumes:
  mongo-data: